### PR TITLE
Updating navigation for framework

### PR DESCRIPTION
**Pull request by kateefly**
@f8f8ff did you want to link the h4 headings in the navigation as well?

### CODE REVIEW

**Comment by kateefly** [comment]
@billmcmillin @scottythered , would one of you be able to check that the navigation for the Framework section works ok?

**Comment by scottythered** [comment]
On the Heroku site, I get page-not-found errors for several.

**Comment by scottythered** [comment]
image

**Comment by kateefly** [comment]
@scottythered I actually just merged the commit which added Framework as a submodule so it wouldn't have been there. Which actually makes this only something that can be reviewed locally (and if you can't do this, that's ok!).

**Comment by f8f8ff** [comment]
Hi @scottythered and @billmcmillin : would one of you be able to review and (hopefully) approve this today? I'd like to be able to share it with the framework group for content review prior to our meeting tomorrow. Thanks!

**Comment by kateefly** [comment]
@cmh2166

**Pull request merged**
